name: Deploy Web Application

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  pull_request:
    paths:
      - 'web/**'

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: docker://node:24
        

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Build Code
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: web/dist

  deploy:
    name: Deploy to Cloudflare Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_ACCOUNT_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'slip-vault'
          directory: 'dist'
